### ISSUE TITLE
Log spammed in case robot is offline

### ISSUE THREAD

**Issue by patman15** [xeniter/romy#4]
Hi!

Thanks for the library! I noticed one issue, my home assistant log is spammed with log messages in case the robot is offline. Since the library raises an exception, I'm not sure if level `WARNING` and `ERROR` is the right one. I'd suggest `DEBUG`? Probably querying multiple further elements after `self.romy_async_query("get/status")` failed with timeout is not reasonable as well?
If you want me to propose a PR, let me know.

```
2024-xx-xx 19:26:36.497 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:36.497 ERROR (MainThread) [romy.romy] FOMY function async_update -> async_query response: timeout
2024-xx-xx 19:26:39.499 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:39.500 ERROR (MainThread) [romy.romy] ROMY function async_update -> async_query response: timeout
2024-xx-xx 19:26:42.502 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:42.502 ERROR (MainThread) [romy.romy] ROMY function async_update -> async_query response: timeout
2024-xx-xx 19:26:50.499 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:50.500 ERROR (MainThread) [romy.romy] ROMY function async_update -> async_query response: timeout
2024-xx-xx 19:26:53.502 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:53.502 ERROR (MainThread) [romy.romy] FOMY function async_update -> async_query response: timeout
2024-xx-xx 19:26:56.505 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:56.506 ERROR (MainThread) [romy.romy] ROMY function async_update -> async_query response: timeout
2024-xx-xx 19:26:59.508 WARNING (MainThread) [romy.utils] ROMY robot timed out
2024-xx-xx 19:26:59.508 ERROR (MainThread) [romy.romy] ROMY function async_update -> async_query response: timeout
```
Thanks!

**Comment by xeniter** [comment]
hi, thanks for the report and sorry for the spam

created branch which logs only one error now when robot went offline
https://github.com/xeniter/romy/pull/5
please take a look, if its ok i will tag and increase romy version in home assistant

**Comment by xeniter** [comment]
created new release https://github.com/xeniter/romy/releases/tag/0.0.10
and PR in home assistant https://github.com/home-assistant/core/pull/114785

**Comment by xeniter** [comment]
got merged now into HA:
https://github.com/home-assistant/core/pull/114934
